### PR TITLE
whoops we broke this

### LINKED ISSUE #533: import-data should only show writable workspaces
This was implemented in #521, but it's broken now. I'm guessing #525 broke this.

Repro:
- https://test-data-explorer.appspot.com/
- Click on export button. (This redirects to import-data with no `ad` param.)
- Workspace dropdown shows 110 workspaces instead of 5

### PR DESCRIPTION
**Pull request by MattPutnam**
and be we I mean I

fixes #533

### CODE REVIEW

File: src/pages/ImportData.js [hunk 1]
```diff
@@ -27,6 +27,7 @@ class Importer extends Component {
           div({}, [
             h(WorkspaceSelector, {
               authorizationDomain: ad,
+              filter: ({ accessLevel }) => Utils.canWrite(accessLevel),
```
Comment (zarsky-broad) [inline src/pages/ImportData.js:30]: `filter: Utils.canWrite` ?

**Review by zarsky-broad — APPROVED** [review]

File: src/pages/ImportData.js (hunk 1 above)
Comment (MattPutnam) [reply src/pages/ImportData.js:30]: We'd have to make that function accept a workspace object. Which we could do, I thought about it.

Comment (zarsky-broad) [reply src/pages/ImportData.js:30]: Ah, right, nvm.
