### PR TITLE
State History fixes

### LINKED ISSUE #227: Consider clearing history state when an error occurs
Once I encountered this error, it was difficult to clear. I had to navigate "forward."

### LINKED ISSUE #232: StateHistory leaks unauthorized info
1. Log in as User A and go to a workspace tab that uses StateHistory. Example: Log in as b.adm.firec and go to son-of-jimmy/notebooks.
2. Log out from this page, and log in as User B who doesn't have access to this workspace
3. Observe that although we get the error message, we still see the notebook cards.

Proposal: logging in clears all history

### PR DESCRIPTION
**Pull request by MattPutnam**
Fixes #227 
Fixes #232 

* Clear all history on sign out
* Option to blast current history and reload on viewing error detail

### CODE REVIEW

File: src/libs/state-history.js [hunk 1]
```diff
@@ -3,3 +3,10 @@ export const set = newState => { window.history.replaceState(newState, '') }
 export const get = () => window.history.state || {}
 
 export const update = newState => { set({ ...get(), ...newState }) }
+
+export const clearCurrent = () => set({})
+
+export const clearAll = () => {
+  window.history.go(-window.history.length)
```
Comment (panentheos) [inline src/libs/state-history.js]: This should probably be `1 - window.history.length`, but even so, do we know that this will work? If the user came from another site, then popping the history will unload the current page, at which point this code probably stops running.

File: src/libs/state-history.js [hunk 2]
```diff
@@ -1,5 +1,54 @@
...
+    window.history.replaceState({ key }, '')
+    return key
+  }
+}
+
+
+export const get = () => {
+  const fetched = sessionStorage.getItem(getKey())
+  if (fetched) {
+    return JSON.parse(fetched).value
```
Comment (panentheos) [inline src/libs/state-history.js:20]: FYI, if these values do get large, then JSON parsing time can become significant. Just something to keep an eye on.

**Review by panentheos — APPROVED** [review]
Looks good.

File: src/libs/__mocks__/state-history.js [hunk 3]
```diff
@@ -0,0 +1,5 @@
+export const get = () => ({})
```
Comment (zarsky-broad) [inline src/libs/__mocks__/state-history.js:1]: Can we not just auto-mock this file?

File: src/libs/state-history.js (hunk 2 above)
Comment (zarsky-broad) [reply src/libs/state-history.js:20]: Should we make `get` async?

File: src/libs/state-history.js [hunk 4]
```diff
@@ -1,5 +1,54 @@
...
+        console.error(error)
+        return
+      } else {
+        const oldest = _.flow(
+          _.mapValues(JSON.parse),
+          _.toPairs,
+          _.sortBy(p => p[1].timestamp),
+          _.first
+        )(sessionStorage)
+        sessionStorage.removeItem(oldest[0])
```
Comment (zarsky-broad) [inline src/libs/state-history.js]: Instead of wrapping this in a loop, can we just have it call itself here?

Comment (zarsky-broad) [reply src/libs/state-history.js]: Also, can we make a note of why we have to do `oldest[0]` instead of oldest here?

**Review by zarsky-broad — APPROVED** [review]

File: src/libs/__mocks__/state-history.js (hunk 3 above)
Comment (MattPutnam) [reply src/libs/__mocks__/state-history.js:1]: No, I need `get` to return an empty map.

File: src/libs/state-history.js (hunk 2 above)
Comment (MattPutnam) [reply src/libs/state-history.js:20]: Sounds like a good idea

File: src/libs/__mocks__/state-history.js (hunk 3 above)
Comment (zarsky-broad) [reply src/libs/__mocks__/state-history.js:1]: If we leave the other methods blank in this file, will they get automocked?

File: src/libs/state-history.js (hunk 4 above)
Comment (MattPutnam) [reply src/libs/state-history.js]: I was concerned about the potential for a stack overflow -- if you try to store something huge and there's only little stuff in storage, it could need to delete a lot. I'll work on making the logic clearer.

Comment (zarsky-broad) [reply src/libs/state-history.js]: Gotcha.

Comment (zarsky-broad) [reply src/libs/state-history.js]: Why not try setting a character length limit? If the string is over 1000 characters, we can just refuse to save it

Comment (MattPutnam) [reply src/libs/state-history.js]: Maybe. @panentheos @dmohs thoughts?

File: src/libs/state-history.js (hunk 2 above)
Comment (panentheos) [reply src/libs/state-history.js:20]: That won't work the way you're thinking. The parsing is still a synchronous blocking operation, unless you do it in a web worker (which has all sorts of other complications)

File: src/libs/__mocks__/state-history.js (hunk 3 above)
Comment (MattPutnam) [reply src/libs/__mocks__/state-history.js:1]: Seems like no.

File: src/libs/state-history.js (hunk 4 above)
Comment (panentheos) [reply src/libs/state-history.js]: Having a low limit would exclude a lot of server response data, which is one of the main things this is being used for. I think the overall logic here is decent, though the `while(true)` is slightly unfortunate. I think you could get around that with a `do while`, but I don't know if that's necessarily an improvement.

Comment (MattPutnam) [reply src/libs/state-history.js]: We could use our own storage, in which case we could use a queue and forgo storing the date and parsing and all of that.

Comment (zarsky-broad) [reply src/libs/state-history.js]: ~~My logic behind 1000 characters is that session storage is limited in most browsers to 5000 characters total. Just thinking out loud.~~
Oh wow, I misunderstood. The limit is 5,000,000 characters. [Never mind...](https://thumbs.gfycat.com/VastDifficultAfricanhornbill-max-1mb.gif)
