### PR TITLE
Better messaging for cluster loading/errors

### LINKED ISSUE #613: Creating and updating cluster doesn't give user enough feedback
While updating the runtime specs of a cluster, I clicked to open a notebook. The opening page stuck around for so long that I thought it had failed, but a few minutes later the notebook opened. I think that we should give more feedback to the user (animations, etc) to let them know that their notebook is actually opening.

screen shot 2018-09-06 at 11 32 05 am

### PR DESCRIPTION
**Pull request by MattPutnam**
Fixes #613 

* Errors from step 1 are shown inline, rather than as a popup
* When the cluster is in the "Creating" state, we get more info

Not 100% where we want it to be, but an improvement. We can file a separate overhaul ticket once we have design for it.

### CODE REVIEW

File: src/pages/workspaces/workspace/notebooks/NotebookLauncher.js [hunk 1]
```diff
@@ -136,7 +139,13 @@ class NotebookEditor extends Component {
     window.addEventListener('beforeunload', this.beforeUnload)
 
     try {
-      const { clusterName, clusterUrl } = await this.startCluster()
+      const { clusterName, clusterUrl, error } = await this.startCluster()
+
+      if (error) {
+        this.setState({ clusterError: error, failed: true })
+        return
```
Comment (panentheos) [inline src/pages/workspaces/workspace/notebooks/NotebookLauncher.js:178]: nit: since this is an error case, it might be slightly clearer if it was handled via a rejection with a special value

**Review by panentheos — APPROVED** [review]
Looks good.
