### PR TITLE
Fix gradient for Safari

### LINKED ISSUE #853: Safari css framing
Looks like the content framing in Safari craps out - too much gray...

### PR DESCRIPTION
**Pull request by MattPutnam**
Fixes #853 

Apparently, Safari treats "transparent" as "transparent black", so we fade through black on our way across the gradient.

### CODE REVIEW

File: src/components/common.js [hunk 1]
```diff
@@ -247,15 +247,15 @@ export const FadeBox = ({ fadePoint = '60%', style = {}, children }) => {
...
+    backgroundColor = 'rgba(255,255,255,0)',
     borderColor = colors.gray[3],
     ...containerStyle
   } = style
 
   return div({
     style: {
       display: 'flex', flexDirection: 'column',
-      background: `linear-gradient(to bottom, white 0%, ${backgroundColor} ${fadePoint}`,
+      background: `linear-gradient(to bottom, white, ${backgroundColor} ${fadePoint})`,
```
Comment (MattPutnam) [inline src/components/common.js:258]: Non functional, just cleanup

**Review by zarsky-broad — APPROVED** [review]

**Review by panentheos — APPROVED** [review]
Looks good.

**Review by elizzhao — APPROVED** [review]
