### PR TITLE
Fix create card in list view

### LINKED ISSUE #628: Create new Workspace/Tool/Notebook should be card in list view
To match Lou's designs, when a user clicks List view for Workspaces, Tools, or Notebooks, the "Create a New [Notebook, Workspace, Tool]" should still be a card:

not a list:

### PR DESCRIPTION
**Pull request by katevoss**
Fixes #628 

I implemented this in Notebooks and Workspace list view, since Tools doesn't have a create card yet.

### CODE REVIEW

File: src/pages/workspaces/List.js [hunk 1]
```diff
@@ -191,16 +182,15 @@ export const WorkspaceList = ajaxCaller(class WorkspaceList extends Component {
...
-          _.map(workspace => {
-            return h(WorkspaceCard, { listView, workspace, key: workspace.workspace.workspaceId })
-          }, data),
-          !isDataLoaded && spinnerOverlay
-        ]),
+          listView ?
+            div({ style: { flex: 1, minWidth: 0, margin: '0.75rem 1rem 0rem 0.75rem' } },
+              renderedWorkspaces
+            ) : renderedWorkspaces
+        ]), !isDataLoaded && spinnerOverlay,
```
Comment (panentheos) [inline src/pages/workspaces/List.js]: nit: For readability it's nice to stay consistent with line breaks. The spinner should probably be on its own line since it's a peer of the card container.

File: src/pages/workspaces/List.js [hunk 2]
```diff
@@ -191,16 +182,15 @@ export const WorkspaceList = ajaxCaller(class WorkspaceList extends Component {
...
             onClick: () => this.setState({ creatingNewWorkspace: true })
           }),
-          _.map(workspace => {
-            return h(WorkspaceCard, { listView, workspace, key: workspace.workspace.workspaceId })
-          }, data),
-          !isDataLoaded && spinnerOverlay
-        ]),
+          listView ?
+            div({ style: { flex: 1, minWidth: 0, margin: '0.75rem 1rem 0rem 0.75rem' } },
+              renderedWorkspaces
```
Comment (panentheos) [inline src/pages/workspaces/List.js]: nit: This technically works because `renderedWorkspaces` is an array, but for clarity we should probably have an extra pair of brackets that serve as the 'children' collection.

**Review by panentheos — APPROVED** [review]
Looks good. (A couple stylistic nits)

File: src/pages/workspaces/List.js (hunk 2 above)
Comment (katevoss) [reply src/pages/workspaces/List.js]: Should I put an extra pair of brackets on both instances of `renderedWorkspaces`?
