### PR TITLE
link to firecloud job details

### LINKED ISSUE #170: (Temporary) Access to job details for a submission
If a workflow submission includes failed jobs, the user needs to inspect these failures so that she can can debug the underlying error. Users also need to abort jobs that are running which may have been misconfigured, in order to avoid wasted spend.

Therefore, we will put a  link to job details on each submission in the submissions history.

Ultimately, we this link will bring users to a filtered view of the Saturn Job Manager to accomplish these goals. However, this work is blocked on technical implementation of a secure Cromwell as a Service with JM pointed at this.

We want users to be able to try out job running while progress is made on JM. Therefore we should temporarily implement this link pointing to the appropriate submissions summary page in the FireCloud version of the current project.

### PR DESCRIPTION
**Pull request by panentheos**
Fixes #170

### CODE REVIEW

File: src/pages/workspaces/workspace/JobHistory.js [hunk 1]
```diff
@@ -153,19 +154,36 @@ class JobHistoryContent extends Component {
...
+              headerRenderer: () => h(HeaderCell, ['Job']),
               cellRenderer: ({ rowIndex }) => {
-                const { methodConfigurationNamespace, methodConfigurationName, submitter } = submissions[rowIndex]
-                return div({}, [
-                  div({}, [
-                    methodConfigurationNamespace !== namespace && span({ style: styles.deemphasized }, [
-                      `${methodConfigurationNamespace}/`
+                const { methodConfigurationNamespace, methodConfigurationName, submitter, submissionId } = submissions[rowIndex]
+                return h(Fragment, [
+                  div([
```
Comment (zarsky-broad) [inline src/pages/workspaces/workspace/JobHistory.js:161]: Do we not want to leave the empty props for consistency? I'm fine with not, I just thought at some point we had said we would.

**Review by zarsky-broad — APPROVED** [review]

**Review by MattPutnam — APPROVED** [review]
Maybe make the link open in a new tab?

File: src/pages/workspaces/workspace/JobHistory.js (hunk 1 above)
Comment (panentheos) [reply src/pages/workspaces/workspace/JobHistory.js:161]: I think it was `children` always being an array that I was pushing for, because hyperscript is particular about types.

**Comment by panentheos** [comment]
I believe we wanted this to open in the same tab, but I'll check and make a followup change if not.
