### PR TITLE
Retry workflow failures

### LINKED ISSUE #424: Rerun workflow failures
Users have repeatedly asked for the ability to rerun just the failed jobs from a submission. For example, say 10% of their workflows failed due to a transient error. They want a single-click relaunch that would issue a new submission recreating just those workflows. How are we identifying such workflows? How are we creating the new submission out of them? This will require eng design!

See the UI affordance in the submission list-entry dropdown from invision:
https://projects.invisionapp.com/d/main#/console/13746874/304975026/preview

### PR DESCRIPTION
**Pull request by MattPutnam**
fixes #424

### CODE REVIEW

File: src/pages/workspaces/workspace/tools/FailureRerunner.js [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+    ])
+
+    toastProps.set({ text: 'Creating set from failures...' })
+
+    const failedEntities = _.flow(
+      _.filter({ status: 'Failed' }),
+      _.map('workflowEntity')
+    )(workflows)
+
+    const newSetName = `${configName}-${submissionId.slice(0, 5)}-resubmission`
```
Comment (MattPutnam) [inline src/pages/workspaces/workspace/tools/FailureRerunner.js]: Current source of errors: If you try to rerun the same one twice, the second one bombs because of a duplicate entity name

File: src/pages/workspaces/workspace/tools/FailureRerunner.js [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+    const newSetType = submissionEntity.entityType
+    const newSet = {
+      name: newSetName,
+      entityType: newSetType,
+      attributes: {
+        [`${failedEntities[0].entityType}s`]: {
```
Comment (MattPutnam) [inline src/pages/workspaces/workspace/tools/FailureRerunner.js:61]: scary

File: src/pages/workspaces/workspace/tools/FailureRerunner.js [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+    }
+
+    await workspace.createEntity(newSet)
+
+    toastProps.set({ text: 'Launching new job...' })
+
+    await methodConfig.launch({
+      entityName: newSetName,
+      entityType: newSetType,
+      expression: newSetType !== rootEntityType ? `this.${rootEntityType}s` : undefined,
```
Comment (MattPutnam) [inline src/pages/workspaces/workspace/tools/FailureRerunner.js:75]: also scary

File: src/pages/workspaces/workspace/tools/FailureRerunner.js [hunk 4]
```diff
@@ -0,0 +1,88 @@
...
+import { div, h } from 'react-hyperscript-helpers'
+import { icon, spinner } from 'src/components/icons'
+import { popNotification, pushNotification } from 'src/components/Notifications'
+import colors from 'src/libs/colors'
+import { reportError } from 'src/libs/error'
+import * as Utils from 'src/libs/utils'
+import { Component } from 'src/libs/wrapped-components'
+
+
+const toastProps = Utils.atom(undefined)
```
Comment (panentheos) [inline src/pages/workspaces/workspace/tools/FailureRerunner.js:12]: Having this as an atom means that it's effectively a singleton, and would probably behave weirdly if you tried to do multiple relaunches at once. Could we use a ref on the `ToastMessageComponent` and push this into per-component state instead?

File: src/pages/workspaces/workspace/tools/FailureRerunner.js (hunk 1 above)
Comment (panentheos) [reply src/pages/workspaces/workspace/tools/FailureRerunner.js]: Should this include a random portion to avoid the collision? Alternatively, could we leverage the fact that the name is predictable and re-use it if it's already there?

File: src/pages/workspaces/workspace/JobHistory.js [hunk 5]
```diff
@@ -181,15 +187,21 @@ const JobHistory = _.flow(
...
-                        div({ style: { marginLeft: '0.5rem' } }, ['View job details'])
-                      ]),
+                      }, [menuIcon('circle-arrow right'), 'View job details']),
+                      isTerminal(status) && workflowStatuses['Failed'] &&
+                      submissionEntity && submissionEntity.entityType.endsWith('_set') && h(MenuButton, {
+                        onClick: () => rerunFailures({
+                          namespace, name, submissionId,
+                          configNamespace: methodConfigurationNamespace, configName: methodConfigurationName,
+                          onDone: () => this.refresh(),
+                          ajax: { Workspaces }
```
Comment (panentheos) [inline src/pages/workspaces/workspace/JobHistory.js]: Passing this means that the ajax flow could get interrupted if this component unmounts, e.g. page transition. Perhaps this is one of the cases where we want to use the non-signal version?

Comment (MattPutnam) [reply src/pages/workspaces/workspace/JobHistory.js]: Good idea.

File: src/pages/workspaces/workspace/tools/FailureRerunner.js (hunk 4 above)
Comment (MattPutnam) [reply src/pages/workspaces/workspace/tools/FailureRerunner.js:12]: I tried that and couldn't get it to work. I'll try again.

File: src/pages/workspaces/workspace/tools/FailureRerunner.js (hunk 1 above)
Comment (MattPutnam) [reply src/pages/workspaces/workspace/tools/FailureRerunner.js]: We could also attach a timestamp.

**Review by panentheos — APPROVED** [review]
Looks good.
