### PR TITLE
relaunch failures also includes aborted workflows

### LINKED ISSUE #1266: Re-run failures doesn't re-run aborted jobs
Re-run failures has been working great for me. I used to create a sample set out of the failed samples, and then re-run a workflow on that sample set. 

I had a case recently where I was running around ~2000 workflows, but needed to kill them off halfway to free up some compute resources. It ended up about ~50% succeeded, ~10% failed, and 40% aborted. 

I wanted a quick way to re-run the failed+aborted jobs. Right now, clicking re-run failures in job manager just re-ran the ~10% that failed left the ~40% that aborted alone.

### PR DESCRIPTION
**Pull request by elizzhao**
Resolves #1266 

Either this or #1602 will need to accommodate for the other since they both touch the relaunch failures button code.

### CODE REVIEW

File: src/pages/workspaces/workspace/tools/FailureRerunner.js [hunk 1]
```diff
@@ -46,7 +46,7 @@ export const rerunFailures = async ({ namespace, name, submissionId, configNames
     ])
 
     const failedEntities = _.flow(
-      _.filter({ status: 'Failed' }),
+      _.filter(v => { return (v.status === 'Aborted' || v.status === 'Failed') }),
```
Comment (panentheos) [inline src/pages/workspaces/workspace/tools/FailureRerunner.js]: nit: since this is a short, single-expression function, it would be clearer without the braces/return.

**Review by panentheos — APPROVED** [review]
Looks good.
